
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for T_ACCOUNT
-- ----------------------------
DROP TABLE IF EXISTS `T_ACCOUNT`;
CREATE TABLE `T_ACCOUNT` (
  `AID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `PROP` varchar(4) NOT NULL DEFAULT '1' COMMENT '账户类别 1，资产，2负债',
  `OWNER` varchar(255) NOT NULL COMMENT '所有者，中文名称',
  `ACCNAME` varchar(255) DEFAULT NULL COMMENT '账户中文名称',
  `ACCOUNT` varchar(20) NOT NULL COMMENT '账户',
  `BALANCE` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '余额',
  `MTYPE` varchar(10) NOT NULL DEFAULT 'CNY' COMMENT '币种CNY|USD|HKD',
  `REMARK` varchar(255) DEFAULT NULL,
  `CREATETIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATETIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `OPERATER` varchar(128) NOT NULL COMMENT '操作者',
  `IFUSE` varchar(2) NOT NULL DEFAULT '0' COMMENT '是否删除了0正常；-1已经删除',
  `ORDERNUM` int(3) NOT NULL DEFAULT '0' COMMENT '页面排序',
  PRIMARY KEY (`AID`)
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8;
