
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for T_WATER
-- ----------------------------
DROP TABLE IF EXISTS `T_WATER`;
CREATE TABLE `T_WATER` (
  `WID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `AID` bigint(20) DEFAULT NULL COMMENT '账户外键',
  `TRDATE` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '交易时间',
  `TRADEKIND` varchar(10) DEFAULT NULL COMMENT '0转账；1居家；2食品；3交通；4投资；5还款',
  `TRTYPE` varchar(10) DEFAULT NULL COMMENT '交易类型0出金；1入金',
  `WACCOUNT` varchar(255) DEFAULT NULL,
  `WACCNAME` varchar(255) DEFAULT NULL,
  `TRNUM` decimal(9,2) NOT NULL DEFAULT '0.00' COMMENT '交易金额',
  `REMARK` varchar(255) DEFAULT NULL COMMENT '交易摘要',
  `OPPID` bigint(20) DEFAULT NULL,
  `CREATETIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATETIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `DEL` varchar(2) NOT NULL DEFAULT '0' COMMENT '是否可以0可用;-1删除',
  PRIMARY KEY (`WID`)
) ENGINE=InnoDB AUTO_INCREMENT=138 DEFAULT CHARSET=utf8;
